name: Create Azure Storage Account

on:
  push:
    branches:
      - main

jobs:
  create-storage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform -chdir=infra init

    - name: Apply Terraform to create storage
      run: terraform -chdir=infra apply -auto-approve

    - name: Output storage account key
      id: storage-key
      run: echo "##[set-output name=storage_key;]$(terraform -chdir=infra output -raw storage_account_primary_access_key)"

    - name: Output storage account name
      id: storage-name
      run: echo "##[set-output name=storage_name;]$(terraform -chdir=infra output -raw storage_account_name)"

    - name: Output resource group name
      id: resource-group
      run: echo "##[set-output name=resource_group;]$(terraform -chdir=infra output -raw resource_group_name)"

    - name: Create storage key secret
      uses: nikhilsbhat/create-secret-action@v1
      with:
        name: AZURE_STORAGE_KEY
        secret: ${{ steps.storage-key.outputs.storage_key }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create storage account name secret
      uses: nikhilsbhat/create-secret-action@v1
      with:
        name: AZURE_STORAGE_ACCOUNT
        secret: ${{ steps.storage-name.outputs.storage_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create resource group name secret
      uses: nikhilsbhat/create-secret-action@v1
      with:
        name: AZURE_RESOURCE_GROUP
        secret: ${{ steps.resource-group.outputs.resource_group }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
