name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create storage account
      run: |
        az group create --name myResourceGroup --location EastUS
        az storage account create --name mystorageaccount --resource-group myResourceGroup --location EastUS --sku Standard_LRS
        az storage container create --name terraform-state --account-name mystorageaccount

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      env:
        ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: terraform -chdir=infra init

    - name: Apply Terraform
      env:
        ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: terraform -chdir=infra apply -auto-approve

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myAppService'
        package: '.'
