name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init -backend-config="resource_group_name=tfstate-resources-franco1" -backend-config="storage_account_name=tfstatedpocfran1" -backend-config="container_name=tfstate-franco1" -backend-config="key=terraform.tfstate"

    - name: Apply Terraform
      run: terraform apply -auto-approve || echo "Infra already exists"
