name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      working-directory: ./infra
      run: terraform init

    - name: Apply Terraform
      working-directory: ./infra
      run: terraform apply -auto-approve || echo "Infra already exists"

  # Optional: Verify infra status and skip deployment if exists
  verify_infra:
    name: 'Verify Infrastructure'
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Verify if infra exists
      run: |
        RESOURCE_GROUP_EXISTS=$(az group exists --name webapppocfranc-resources)
        if [ "$RESOURCE_GROUP_EXISTS" == "true" ]; then
          echo "Infrastructure already exists"
          exit 0
        else
          echo "Deploying infrastructure"
          exit 1
        fi
